### ISSUE TITLE
Install via npm fail on Ubuntu 

### ISSUE THREAD

**Issue by simonchapman1986** [eugeneware/ffmpeg-static#45]
```$ sudo npm install -g ffmpeg-static
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine ffmpeg-static@4.2.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine ffmpeg-static@4.2.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"
> ffmpeg-static@4.2.1 install /usr/local/lib/node_modules/ffmpeg-static
> node install.js

/usr/local/lib/node_modules/ffmpeg-static/install.js:52
  url = new URL(url)
  ^

ReferenceError: URL is not defined
    at normalizeS3Url (/usr/local/lib/node_modules/ffmpeg-static/install.js:52:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/ffmpeg-static/install.js:61:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! Linux 4.15.0-1065-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ffmpeg-static"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! ffmpeg-static@4.2.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffmpeg-static@4.2.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ffmpeg-static package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffmpeg-static
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ffmpeg-static
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log```

```1983 silly install ffmpeg-static@4.2.1 /usr/local/lib/node_modules/.staging/ffmpeg-static-dbdeacf8
1984 info lifecycle ffmpeg-static@4.2.1~install: ffmpeg-static@4.2.1
1985 verbose lifecycle ffmpeg-static@4.2.1~install: unsafe-perm in lifecycle false
1986 verbose lifecycle ffmpeg-static@4.2.1~install: PATH: /usr/share/npm/bin/node-gyp-bin:/usr/local/lib/node_modules/ffmpeg-static/node_modules/.bin:/usr/local/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
1987 verbose lifecycle ffmpeg-static@4.2.1~install: CWD: /usr/local/lib/node_modules/ffmpeg-static
1988 silly lifecycle ffmpeg-static@4.2.1~install: Args: [ '-c', 'node install.js' ]
1989 silly lifecycle ffmpeg-static@4.2.1~install: Returned: code: 1  signal: null
1990 info lifecycle ffmpeg-static@4.2.1~install: Failed to exec install script
1991 verbose unlock done using /home/ubuntu/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
1992 silly rollbackFailedOptional Starting
1993 silly rollbackFailedOptional Finishing
1994 silly runTopLevelLifecycles Starting
1995 silly runTopLevelLifecycles Finishing
1996 silly install printInstalled
1997 verbose stack Error: ffmpeg-static@4.2.1 install: `node install.js`
1997 verbose stack Exit status 1
1997 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
1997 verbose stack     at emitTwo (events.js:126:13)
1997 verbose stack     at EventEmitter.emit (events.js:214:7)
1997 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
1997 verbose stack     at emitTwo (events.js:126:13)
1997 verbose stack     at ChildProcess.emit (events.js:214:7)
1997 verbose stack     at maybeClose (internal/child_process.js:925:16)
1997 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1998 verbose pkgid ffmpeg-static@4.2.1
1999 verbose cwd /home/ubuntu
2000 error Linux 4.15.0-1065-aws
2001 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "ffmpeg-static"
2002 error node v8.10.0
2003 error npm  v3.5.2
2004 error code ELIFECYCLE
2005 error ffmpeg-static@4.2.1 install: `node install.js`
2005 error Exit status 1
2006 error Failed at the ffmpeg-static@4.2.1 install script 'node install.js'.
2006 error Make sure you have the latest version of node.js and npm installed.
2006 error If you do, this is most likely a problem with the ffmpeg-static package,
2006 error not with npm itself.
2006 error Tell the author that this fails on your system:
2006 error     node install.js
2006 error You can get information on how to open an issue for this project with:
2006 error     npm bugs ffmpeg-static
2006 error Or if that isn't available, you can get their info via:
2006 error     npm owner ls ffmpeg-static
2006 error There is likely additional logging output above.
2007 verbose exit [ 1, true ]```

**Comment by derhuerst** [comment]
You‘re using an outdated version (`8`) of Node.js, as the warning says at the very top. `ffmpeg-static` requires at least version `10`.
